# Generated by Django 2.1.7 on 2019-03-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0003_multiplechoicequestionmodel_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestionmodel',
            old_name='categories',
            new_name='category',
        ),
    ]
