# Generated by Django 2.1.7 on 2019-03-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0004_auto_20190325_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestionmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
