# Generated by Django 2.1.7 on 2019-03-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0006_auto_20190325_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleChoiceQuestionModel',
            new_name='QuestionModel',
        ),
    ]
