# Generated by Django 2.1.7 on 2019-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0007_auto_20190325_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='choice_5',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='choice_6',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='choice_3',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='choice_4',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
