# Generated by Django 2.1.7 on 2019-03-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0008_auto_20190325_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='choice_1',
            field=models.CharField(default='True', max_length=256),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='choice_2',
            field=models.CharField(default='False', max_length=256),
        ),
    ]
