# Generated by Django 2.1.7 on 2019-03-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0009_auto_20190330_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('createdDate', models.DateField()),
                ('question', models.ManyToManyField(to='maker.QuestionModel')),
            ],
        ),
    ]
