# Generated by Django 2.1.7 on 2019-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0011_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
