# Generated by Django 2.1.7 on 2019-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0014_auto_20190418_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='question',
            field=models.ManyToManyField(to='maker.QuestionModel'),
        ),
    ]
