# Generated by Django 2.1.7 on 2019-04-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0015_auto_20190418_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='answer_text',
            field=models.CharField(default='', max_length=256),
        ),
    ]
