# Generated by Django 2.1.7 on 2019-05-02 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maker', '0016_questionmodel_answer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradedTestModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('test', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maker.TestModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
